sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/protobuf

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - PROTOBUF_VERSION=2.6.1

before_install:
    - bash ./tests/travis/install-protobuf.sh

install:
    - composer self-update
    - composer --prefer-source install
    - export PATH=$PATH:$HOME/protobuf/bin/

script:
    - protoc --version
    - uname -a
    - make phpcs proto-generate phpunit-coverage-clover

after_script:
    - ./vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 7.0
